[package]
edition = "2021"
name = "webdog"
version = "0.1.0"

[dependencies]
color-eyre = {version = "0.6", optional = true}
extract-frontmatter = "4"
eyre = "0.6"
fs_extra = "1.2"
futures = {version = "0.3", optional = true}
grass = {version = "0.13", default-features = false}
hotwatch = {version = "0.5", optional = true}
itertools = "0.13"
lol_html = "2"
minifier = {version = "0.3", features = ["html"]}
percent-encoding = {version = "2", optional = true}
pulldown-cmark = {version = "0.12", default-features = false, features = [
  "simd",
  "html",
]}
rayon = "1"
rss = {version = "2", features = ["validation"]}
serde = {version = "1", features = ["derive"]}
serde_yml = "0.0.12"
syntect = "5"
tera = "1"
time = {version = "0.3", features = ["serde-human-readable"]}
tokio = {version = "1.10", features = [
  "macros",
  "rt-multi-thread",
], optional = true}
url = {version = "2", features = ["serde"]}
walkdir = "2"
warp = {version = "0.3", optional = true}

[features]
default = ["serve", "color-eyre"]
serve = ["futures", "hotwatch", "percent-encoding", "tokio", "warp"]
